# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cru < Formula
  desc "utility to update container image references"
  homepage "https://github.com/binxio/cru"
  version "2.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/binxio/cru/releases/download/2.0.2/cru_2.0.2_darwin_arm64.tar.gz"
      sha256 "fd23b001869632d2324f1d455e7d864476e6e6a378d07d1b2ff056b0559253c2"

      def install
        bin.install "cru"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/binxio/cru/releases/download/2.0.2/cru_2.0.2_darwin_amd64.tar.gz"
      sha256 "457fc3d293b4d1bc7c5cf7bfa683b2790c4e8413103f796b98a51c934c58a51d"

      def install
        bin.install "cru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/binxio/cru/releases/download/2.0.2/cru_2.0.2_linux_arm64.tar.gz"
      sha256 "779e19239f4add7d19c1a15280c4da85abf03c59cfbe09038e3f90c31d9d5b35"

      def install
        bin.install "cru"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/binxio/cru/releases/download/2.0.2/cru_2.0.2_linux_amd64.tar.gz"
      sha256 "a810753e8b0f2e4c10892c132c0cb1b21d8198b88eb122a3a2fedc0c0bd15585"

      def install
        bin.install "cru"
      end
    end
  end
end
